name: Publish Python Package

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    github-release:
        name: create github release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Create release
              uses: ncipollo/release-action@v1
              with:
                  generateReleaseNotes: true
                  token: ${{ secrets.GITHUB_TOKEN }}

    publish-to-pypi:
        name: upload release to PyPI
        needs: [github-release]
        runs-on: ubuntu-latest
        environment: pypi
        permissions:
            id-token: write # Needed for OIDC authentication to PyPI
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"
                  cache: pip
            - name: Upgrade build tooling
              run: |
                  python -m pip install --upgrade pip
                  pip install build
            - name: Build package
              run: python -m build
            - name: Publish package
              uses: pypa/gh-action-pypi-publish@release/v1
